---
name: Lintcheck Python
on:
  push:
    branches: [main]
    paths: ['**.py']
  pull_request:
    paths: ['**.py']
jobs:
  check_python:
    name: Check Python linting
    runs-on: ubuntu-latest
    steps:
      - name: Install the latest version of uv.
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"

      - uses: actions/checkout@v4
      - run: uv run ruff format --check --diff .
      - run: uv run ruff check
